name: Sync code to CentOS (single target, no restart)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: production
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}

      # 服务器部署根路径
      REMOTE_BASE: /var/www/fancoolweb

      # 要同步的本地路径（如在子目录，如 apps/web，请改为相对路径）
      LOCAL_PATH: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          if [ -n "$SSH_PORT" ]; then
            ssh-keyscan -p "$SSH_PORT" -H "$SSH_HOST" >> ~/.ssh/known_hosts
          else
            ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
          fi

      - name: Create release directory on server
        shell: bash
        run: |
          ssh -p "${SSH_PORT:-22}" "$SSH_USER@$SSH_HOST" "\
            mkdir -p '${REMOTE_BASE}/releases/${GITHUB_SHA}' \
          "

      - name: Rsync code
        shell: bash
        run: |
          EXCLUDES=(
            "--exclude=.git"
            "--exclude=.github"
            "--exclude=*.log"
            "--exclude=__pycache__"
            "--exclude=*.pyc"
            "--exclude=.venv"
            "--exclude=venv"
            "--exclude=node_modules"
          )
          if [ -f ".deployignore" ]; then
            EXCLUDES+=("--exclude-from=.deployignore")
          fi
          rsync -azP --delete "${EXCLUDES[@]}" -e "ssh -p ${SSH_PORT:-22}" \
            "${LOCAL_PATH}/" "${SSH_USER}@${SSH_HOST}:${REMOTE_BASE}/releases/${GITHUB_SHA}/"

      - name: Done (manual activation required)
        run: |
          echo "Upload finished."
          echo "Next steps on server (execute manually):"
          echo "  ln -sfn ${REMOTE_BASE}/releases/${GITHUB_SHA} ${REMOTE_BASE}/current"
          echo "  sudo systemctl restart fancoolweb fancooladmin"